substitutions:
  device_name: dehu-retrofit
  friendly_name: "Dehumidifier Retrofit"

  # --- As-built Physical Pin Map ---
  pin_dht: D1        # Humidity/Temp Sensor (DHT11/22) DATA
  pin_float: D2      # Bucket Float Switch sense node (shared with ULN I6 for FULL LED)
  pin_adc: A0        # Evaporator NTC Thermistor (Analog)

  pin_fan_high: D0   # Relay: Fan High Speed (ULN input)
  pin_fan_med:  D5   # Relay: Fan Med Speed (ULN input)
  pin_fan_low:  D6   # Relay: Fan Low Speed (ULN input)
  pin_comp:     D7   # Relay: Compressor (ULN input)

  pin_led_req:  RX   # Dehumidification requested LED (ULN input)

  # --- Timing & Safety Constants ---
  startup_lockout_s: "300"    # 5 min delay on power-on for refrigerant settling
  min_off_time_s: "300"       # 5 min anti-short cycle for compressor
  min_on_time_s:  "60"        # 1 min minimum run time to move oil
  rh_integrate_on_s: "60"     # Require RH high for 60s before starting
  fan_runon_s: "45"           # Keep fan on after compressor stops to dry coils
  default_rh_setpoint: "55"   # Target Relative Humidity %
  default_rh_hyst: "5"        # +/- Hysteresis
  auto_fan_med_delta: "5"     # Speed up to Med if RH is 5% over setpoint
  auto_fan_high_delta: "10"   # Speed up to High if RH is 10% over setpoint

  # --- Defrost Parameters ---
  ice_enter_c: "0.0"          # Temperature to trigger defrost logic
  ice_enter_for_s: "90"       # Must stay below ice_enter_c for 90s
  ice_exit_c:  "8.0"          # Temperature to resume normal operation
  ice_exit_for_s: "30"        # Must stay above ice_exit_c for 30s

esp8266:
  board: d1_mini

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}
  on_boot:
    priority: 600
    then:
      - script.execute: all_outputs_off
      - lambda: |-
          id(compressor_allowed) = false;
          id(lockout_end_ms) = millis() + (${startup_lockout_s} * 1000UL);
          id(in_defrost) = false;
          id(rh_high_since_ms) = 0;
          id(comp_on_since_ms) = 0;
          id(defrost_start_ms) = 0;
          id(evap_cold_since_ms) = 0;
          id(evap_warm_since_ms) = 0;
      - delay: ${startup_lockout_s}s
      - lambda: |-
          id(compressor_allowed) = true;
          id(lockout_end_ms) = 0;

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  min_auth_mode: WPA2
  ap:
    ssid: "${device_name} Fallback"

api:

ota:
  - platform: esphome

logger:
  baud_rate: 0  # RX used as GPIO

globals:
  - id: compressor_allowed
    type: bool
    initial_value: "false"
  - id: lockout_end_ms
    type: uint32_t
    initial_value: "0"
  - id: in_defrost
    type: bool
    initial_value: "false"
  - id: evap_cold_since_ms
    type: uint32_t
    initial_value: "0"
  - id: evap_warm_since_ms
    type: uint32_t
    initial_value: "0"
  - id: rh_high_since_ms
    type: uint32_t
    initial_value: "0"
  - id: comp_on_since_ms
    type: uint32_t
    initial_value: "0"
  - id: defrost_start_ms
    type: uint32_t
    initial_value: "0"

  # Persistent stats
  - id: defrost_last_ms
    type: uint32_t
    restore_value: yes
    initial_value: "0"
  - id: defrost_total_ms
    type: uint32_t
    restore_value: yes
    initial_value: "0"
  - id: defrost_count
    type: uint32_t
    restore_value: yes
    initial_value: "0"

output:
  - platform: gpio
    pin: ${pin_led_req}
    id: led_req_out

light:
  - platform: binary
    id: led_dehu_req
    name: "Dehu Requested LED"
    output: led_req_out
    restore_mode: ALWAYS_OFF

select:
  - platform: template
    id: fan_mode_request
    name: "Fan Mode Request"
    options: ["Off", "Auto", "Low", "Med", "High"]
    initial_option: "Auto"
    optimistic: true
    on_value:
      - script.execute: apply_fan_mode

number:
  - platform: template
    id: rh_setpoint
    name: "RH Setpoint"
    unit_of_measurement: "%"
    min_value: 30
    max_value: 80
    step: 1
    initial_value: ${default_rh_setpoint}
    optimistic: true
    restore_value: true

  - platform: template
    id: rh_hyst
    name: "RH Hysteresis"
    unit_of_measurement: "%"
    min_value: 1
    max_value: 10
    step: 1
    initial_value: ${default_rh_hyst}
    optimistic: true
    restore_value: true

switch:
  - platform: gpio
    id: fan_low_relay
    internal: true
    pin: ${pin_fan_low}

  - platform: gpio
    id: fan_med_relay
    internal: true
    pin: ${pin_fan_med}

  - platform: gpio
    id: fan_high_relay
    internal: true
    pin: ${pin_fan_high}

  - platform: gpio
    id: compressor_relay
    internal: true
    pin: ${pin_comp}
    on_turn_on:
      - lambda: |-
          id(comp_on_since_ms) = millis();
    on_turn_off:
      - script.execute: compressor_lockout
      - script.execute: compressor_fan_runon

  - platform: template
    id: dehu_request
    name: "Dehumidify Request"
    restore_mode: RESTORE_DEFAULT_OFF
    optimistic: true
    on_state:
      - lambda: |-
          id(rh_high_since_ms) = 0;
          if (x) {
            id(led_dehu_req).turn_on().perform();
          } else {
            id(led_dehu_req).turn_off().perform();
            id(compressor_relay).turn_off();
            id(in_defrost) = false;
          }
          id(apply_fan_mode).execute();

binary_sensor:
  - platform: gpio
    id: bucket_full
    name: "Bucket Full"
    pin:
      number: ${pin_float}
      mode: INPUT_PULLUP
    filters:
      - delayed_on: 50ms

sensor:
  - platform: dht
    pin: ${pin_dht}
    model: DHT11
    humidity:
      id: rh
      name: "Humidity"
    temperature:
      id: intake_temp
      name: "Intake Temp"
    update_interval: 5s

  - platform: adc
    pin: ${pin_adc}
    id: evap_adc
    filters:
      - multiply: 3.3

  - platform: resistance
    id: evap_resistance
    sensor: evap_adc
    configuration: UPSTREAM
    resistor: 19.91kOhm

  - platform: ntc
    id: evap_temp
    name: "Evap Temp"
    sensor: evap_resistance
    calibration:
      b_constant: 3640
      reference_temperature: 25°C
      reference_resistance: 20kOhm

  - platform: template
    name: "Defrost Count"
    accuracy_decimals: 0
    lambda: |-
      return (float) id(defrost_count);

  - platform: template
    name: "Defrost Last Duration"
    unit_of_measurement: "s"
    lambda: |-
      return (float) (id(defrost_last_ms) / 1000.0);

text_sensor:
  - platform: template
    id: dehu_state
    name: "Dehu State"
  - platform: template
    id: fan_mode_actual
    name: "Fan Mode"

script:
  - id: all_outputs_off
    then:
      - switch.turn_off: fan_low_relay
      - switch.turn_off: fan_med_relay
      - switch.turn_off: fan_high_relay
      - switch.turn_off: compressor_relay

  - id: apply_fan_mode
    mode: restart
    then:
      - lambda: |-
          const bool comp_on = id(compressor_relay).state;
          const bool defrost = id(in_defrost);
          std::string req = id(fan_mode_request).current_option();
          esphome::switch_::Switch* target = nullptr;
          std::string label = "Off";

          if (defrost) {
            target = id(fan_high_relay);
            label = "Defrost High";
          } else if (req == "Low") {
            target = id(fan_low_relay);
            label = "Low";
          } else if (req == "Med") {
            target = id(fan_med_relay);
            label = "Med";
          } else if (req == "High") {
            target = id(fan_high_relay);
            label = "High";
          } else if (req == "Auto") {
            if (comp_on) {
              if (isnan(id(rh).state)) {
                target = id(fan_low_relay);
                label = "Low (Auto/Error)";
              } else {
                float err = id(rh).state - id(rh_setpoint).state;
                if (err >= ${auto_fan_high_delta}) {
                  target = id(fan_high_relay);
                } else if (err >= ${auto_fan_med_delta}) {
                  target = id(fan_med_relay);
                } else {
                  target = id(fan_low_relay);
                }
                label = "Auto";
              }
            } else {
              target = nullptr;
              label = "Off";
            }
          }

          if (comp_on && target == nullptr) {
            target = id(fan_low_relay);
            label = "Low (Compressor)";
          }

          if (id(fan_low_relay).state && target != id(fan_low_relay)) id(fan_low_relay).turn_off();
          if (id(fan_med_relay).state && target != id(fan_med_relay)) id(fan_med_relay).turn_off();
          if (id(fan_high_relay).state && target != id(fan_high_relay)) id(fan_high_relay).turn_off();

          if (target != nullptr && !target->state) target->turn_on();

          id(fan_mode_actual).publish_state(label);

  - id: compressor_lockout
    mode: restart
    then:
      - lambda: |-
          id(compressor_allowed) = false;
          id(lockout_end_ms) = millis() + (${min_off_time_s} * 1000);
      - delay: ${min_off_time_s}s
      - lambda: |-
          id(compressor_allowed) = true;
          id(lockout_end_ms) = 0;

  - id: compressor_fan_runon
    mode: restart
    then:
      - if:
          condition:
            lambda: |-
              return id(dehu_request).state && !id(in_defrost);
          then:
            - lambda: |-
                if (id(fan_med_relay).state) id(fan_med_relay).turn_off();
                if (id(fan_high_relay).state) id(fan_high_relay).turn_off();
                if (!id(fan_low_relay).state) id(fan_low_relay).turn_on();
                id(fan_mode_actual).publish_state("Run-on Drying");
            - delay: ${fan_runon_s}s
            - script.execute: apply_fan_mode

  - id: start_defrost
    then:
      - lambda: |-
          if (id(in_defrost)) return;
          id(in_defrost) = true;
          id(defrost_start_ms) = millis();
          id(defrost_count)++;
      - switch.turn_off: compressor_relay
      - script.execute: apply_fan_mode

  - id: stop_defrost
    then:
      - lambda: |-
          if (!id(in_defrost)) return;
          id(in_defrost) = false;
          if (id(defrost_start_ms) > 0) {
            uint32_t d = millis() - id(defrost_start_ms);
            id(defrost_last_ms) = d;
            id(defrost_total_ms) += d;
            id(defrost_start_ms) = 0;
          }
      - script.execute: apply_fan_mode

interval:
  - interval: 2s
    then:
      - lambda: |-
          // 1) State text
          if (id(in_defrost)) {
            id(dehu_state).publish_state("Defrost");
          } else if (id(bucket_full).state) {
            id(dehu_state).publish_state("Bucket Full");
          } else if (isnan(id(rh).state)) {
            id(dehu_state).publish_state("Bad RH Sensor");
          } else if (id(dehu_request).state) {
            if (!id(compressor_allowed)) {
              int rem = (id(lockout_end_ms) > millis()) ? (id(lockout_end_ms)-millis())/1000 : 0;
              char buf[32];
              sprintf(buf, "Lockout (%ds)", rem);
              id(dehu_state).publish_state(buf);
            } else if (id(compressor_relay).state) {
              id(dehu_state).publish_state("Dehumidifying");
            } else {
              id(dehu_state).publish_state("Idle (Wait RH)");
            }
          } else {
            id(dehu_state).publish_state("Monitor Only");
          }

          // 2) Safety shutdowns
          if (id(bucket_full).state || !id(dehu_request).state || isnan(id(rh).state)) {
            id(compressor_relay).turn_off();
            id(rh_high_since_ms) = 0;
          }
          if (id(compressor_relay).state &&
              !id(fan_low_relay).state &&
              !id(fan_med_relay).state &&
              !id(fan_high_relay).state) {
            id(compressor_relay).turn_off();
          }

          // 3) Defrost logic
          if (id(dehu_request).state && !isnan(id(evap_temp).state)) {
            float t = id(evap_temp).state;
            uint32_t now = millis();
            if (!id(in_defrost)) {
              if (t <= ${ice_enter_c}) {
                if (id(evap_cold_since_ms) == 0) id(evap_cold_since_ms) = now;
                if (now - id(evap_cold_since_ms) >= ${ice_enter_for_s} * 1000) id(start_defrost).execute();
              } else {
                id(evap_cold_since_ms) = 0;
              }
            } else {
              if (t >= ${ice_exit_c}) {
                if (id(evap_warm_since_ms) == 0) id(evap_warm_since_ms) = now;
                if (now - id(evap_warm_since_ms) >= ${ice_exit_for_s} * 1000) id(stop_defrost).execute();
              } else {
                id(evap_warm_since_ms) = 0;
              }
            }
          }

          // 4) Compressor demand (RH check)
          if (!id(in_defrost) && !id(bucket_full).state && !isnan(id(rh).state)) {
            float h = id(rh).state;
            float sp = id(rh_setpoint).state;
            float hy = id(rh_hyst).state;
            uint32_t now = millis();

            if (h > (sp + hy)) {
              if (id(rh_high_since_ms) == 0) id(rh_high_since_ms) = now;
            } else {
              id(rh_high_since_ms) = 0;
            }

            if (!id(compressor_relay).state) {
              if (id(compressor_allowed) && id(rh_high_since_ms) != 0 &&
                  (now - id(rh_high_since_ms) >= ${rh_integrate_on_s} * 1000)) {
                if (!id(fan_low_relay).state &&
                    !id(fan_med_relay).state &&
                    !id(fan_high_relay).state) {
                  id(fan_low_relay).turn_on();
                }
                id(compressor_relay).turn_on();
              }
            } else if (h < (sp - hy) &&
                       (now - id(comp_on_since_ms) >= ${min_on_time_s} * 1000)) {
              id(compressor_relay).turn_off();
            }
          }
      - script.execute: apply_fan_mode
